### ISSUE TITLE
Error on server starting up

### ISSUE THREAD

**Issue by jangaraev** [SagePtr/openserver-php-8.2#1]
I have the following error when switched to PHP8.2 in Open Server:

![image](https://github.com/SagePtr/openserver-php-8.2/assets/101257372/93f66724-65f2-4dbe-8182-a9fb295d63c7)

Environment:
![image](https://github.com/SagePtr/openserver-php-8.2/assets/101257372/c8f326a7-282f-46ad-9ba7-c957dc3cdc76)
![image](https://github.com/SagePtr/openserver-php-8.2/assets/101257372/636ca2b3-f629-43e8-8650-5eb93ae2281a)

**Comment by amalychev** [comment]
I have the same problem

**Comment by amalychev** [comment]
Found the solution here https://ospanel.io/forum/viewtopic.php?p=31767#p31767

**Comment by SagePtr** [comment]
This is caused by an outdated version of Apache shipped with OpenServer. The safest solution is to update Apache:

1. Stop OpenServer.
2. Download the latest Apache 2.4.XX Win64 distribution from here: https://www.apachelounge.com/download/
3. Unpack two directories `bin` and `modules` from downloaded archive into `OSPanel\modules\http\Apache_2.4-PHP_8.0-8.1` overwriting existing files.
4. Start OpenServer.

TODO: ship updated Apache version as separate module and note it in README.

**Comment by SagePtr** [comment]
Added Apache_2.4-PHP_8.2-8.3: https://github.com/SagePtr/openserver-apache-2.4
It should work without issues

**Comment by decadence** [comment]
@SagePtr Thank you! Maybe it's better to add this info into README.md
